version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '{asctime} | {levelname} | {name} | {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  
  errors_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR 
    formatter: simple
    filename: errors.log
    maxBytes: 52428800 #50MB
    backupCount: 3
    encoding: utf8

  detail: #used to log all debug messages
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log
    maxBytes: 52428800 #50MB
    backupCount: 3

loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: 
    - console
    - detail
    - errors_file_handler